### ISSUE TITLE
define location of configuration "application.yaml" as env variable

### ISSUE THREAD

**Issue by freegroup** [Peripli/service-broker-proxy#4]
Hi

at the moment the location is fixed coded to the directory of the application.
A more flexible approach would help in the kubernetes enviroment.
We want to use a config-map and mount them into the docker container. But for this
we need a way to name the location of the *application.yaml* in a more dynamic way.

```go

// Default returns the default environment configuration to be loaded from application.yml
func Default(envPrefix string) *viperEnv {
	configFile := &ConfigFile{
		Path:   ".",
		Name:   "application",
		Format: "yml",
	}
	return New(configFile, envPrefix)
}
```

**Comment by freegroup** [comment]
maybe we can add something like this
```go
viper.AddConfigPath("$SERVICE_BROKER_PROXY_CONF")
```

in
```go
func (v *viperEnv) Load() error {
	v.Viper.AddConfigPath(v.configFile.Path)
	v.Viper.SetConfigName(v.configFile.Name)
	v.Viper.SetConfigType(v.configFile.Format)
	v.Viper.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	v.Viper.SetEnvPrefix(v.envPrefix)
	v.Viper.AutomaticEnv()
	if err := v.Viper.ReadInConfig(); err != nil {
		return fmt.Errorf("could not read configuration file: %s", err)
	}
	return nil
}
````

**Comment by KirilKabakchiev** [comment]
location and name of application.yml can now be configured with pflags (recommended) or env vars. Also everything that can  be defined inside application.yml can also be configured via pflags and env vars
